version: '3.1'

services:

  #docker run -dp 3000:3000 --network nest-api-network -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret nest-api:v1
  app:
    image: node:14.17-alpine3.11
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /nest-docker-build
    volumes:
      - ./:/nest-docker-build
    depends_on: 
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret


  #docker run -d --network nest-api-network --network-alias mongo -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret -e MONGO_INITDB_DATABASE=nest-api-db mongo:4.4
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - nest-api-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes: 
  nest-api-db:    


